stages:
  obter_dados:
    cmd: python -m src.data.get_data customer-service-classifier dataset/tickets_reclamacoes_classificados.csv
      data/raw/tickets_reclamacoes_classificados.csv
    deps:
    - src/data/get_data.py
    outs:
    - data/raw/tickets_reclamacoes_classificados.csv

  processar_dados:
    cmd: python -m src.data.make_dataset data/raw/tickets_reclamacoes_classificados.csv
      data/processed/dataset_processed.csv
    deps:
    - src/data/make_dataset.py
    - data/raw/tickets_reclamacoes_classificados.csv
    outs:
    - data/processed/dataset_processed.csv

  processar_features:
    cmd: python -m src.data.make_feature data/processed/dataset_processed.csv data/processed/dataset_features.csv
    deps:
    - src/data/make_feature.py
    - data/processed/dataset_processed.csv
    outs:
    - data/processed/dataset_features.csv

  treinamento:
    cmd: python -m src.models.train_model data/processed/dataset_features.csv models/model.pkl
    deps:
    - src/models/train_model.py
    - data/processed/dataset_features.csv
    outs:
    - models/model.pkl
artifacts:
  customer-service-classifier:
    path: models/model.pkl
    type: model
    desc: Modelo declassificação de atendimento
    labels:
    - classificação
metrics:
- dvclive/metrics.json
plots:
- dvclive/plots/metrics:
    x: step
